name: my_first_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  url_launcher: ^6.2.1
  path_provider: ^2.1.5 # ✅ macOS 지원 포함된 버전
  just_audio: ^0.9.34
  file_picker: ^5.2.10
  audio_session: ^0.1.14
  youtube_player_flutter: ^8.1.1
  audio_waveforms: ^1.0.6
  flutter_sound_lite: ^8.5.0
  js: ^0.6.5
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
